test_value = "Config is loading correctly"

[extra]
test_message = "Extra section is loading correctly"

base_url = "https://rick90.fulmerites.org"
title = "Happy 80th, Ricky-Boy!"
compile_sass = true
build_search_index = false

[extra]
# Names are stored in display order
names = [
    "01-brian-fulmer",
    "02-jane-fulmer",
    "03-anita-samardich",
    "04-beth-fulmer",
    "05-jack-meyer",
    "06-dick-melstrom",
    "07-kathy-mccurdy",
    "08-bob-van-dellen",
    "09-tom-wendstadt",
    "10-aris-georges",
    "11-joe-calverly",
    "12-karen-jordan",
    "13-john-winn",
    "14-mike-lueder",
    "15-richard-tuxbury",
    "16-penny-thom-robinson",
    "17-brad-bauer",
    "18-anne-bauer",
    "19-raymond-fulmer",
    "20-sophie-baruth",
    "21-esme-leonie-bauer",
    "22-shaun-christa-loic-fulmer",
    "23-ty-fulmer",
    "24-bobbi-ronnie-blackman",
    "25-jill-watson",
    "26-mickey-putman",
    "27-justin-pepper",
    "28-don-pat-rutt",
    "29-jim-jordan",
    "30-susan-hanson",
    "31-mike-kamalowski",
    "32-joseph-baumann",
    "33-regan-oneill",
    "34-jason-raffaele",
    "35-forest-baruth",
    "36-doug-and-deb-iseri",
    "37-tom-long",
    "38-steve-king",
    "39-cathy-lazar-nelson",
    "40-john-lori-phillips",
    "41-alice-fulmer",
    "42-christine-samardich",
    "43-final-message"
]

# This maps slugs to display names
[extra.display_names]
01-brian-fulmer = "Brian Fulmer"
02-jane-fulmer = "Jane Fulmer"
03-anita-samardich = "Anita Samardich"
04-beth-fulmer = "Beth Fulmer"
05-jack-meyer = "Jack Meyer"
06-dick-melstrom = "Dick Melstrom"
07-kathy-mccurdy = "Kathy McCurdy"
08-bob-van-dellen = "Bob Van Dellen"
09-tom-wendstadt = "Tom Wendstadt"
10-aris-georges = "Aris Georges"
11-joe-calverly = "Joe Calverly"
12-karen-jordan = "Karen Jordan"
13-john-winn = "John Winn"
14-mike-lueder = "Mike Lueder"
15-richard-tuxbury = "Richard Tuxbury"
16-penny-thom-robinson = "Penny and Thom Robinson"
17-brad-bauer = "Brad Bauer"
18-anne-bauer = "Anne Bauer"
19-raymond-fulmer = "Raymond Fulmer"
20-sophie-baruth = "Sophie Baruth"
21-esme-leonie-bauer = "Esme and Leonie Bauer"
22-shaun-christa-loic-fulmer = "Shaun Christa Loic Fulmer"
23-ty-fulmer = "Ty Fulmer"
24-bobbi-ronnie-blackman = "Bobbi and Ronnie Blackman"
25-jill-watson = "Jill Watson"
26-mickey-putman = "Mickey Putman"
27-justin-pepper = "Justin Pepper"
28-don-pat-rutt = "Don and Pat Rutt"
29-jim-jordan = "Jim Jordan"
30-susan-hanson = "Susan Hanson"
31-mike-kamalowski = "Mike Kamalowski"
32-joseph-baumann = "Joseph Baumann"
33-regan-oneill = "Regan ONeill"
34-jason-raffaele = "Jason Raffaele"
35-forest-baruth = "Forest Baruth"
36-doug-and-deb-iseri = "Doug and Deb Iseri"
37-tom-long = "Tom Long"
38-steve-king = "Steve King"
39-cathy-lazar-nelson = "Cathy Lazar Nelson"
40-john-lori-phillips = "John and Lori Phillips"
41-alice-fulmer = "Alice Fulmer"
42-christine-samardich = "Christine Samardich"
43-final-message = "Final Message"
