name: Deploy Zola site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Zola
        run: |
          wget -q -O - \
            "https://github.com/getzola/zola/releases/download/v0.17.2/zola-v0.17.2-x86_64-unknown-linux-gnu.tar.gz" \
            | tar xzf - -C /usr/local/bin

      - name: Debug Info
        run: |
          echo "===== Current directory ====="
          pwd
          echo "===== Directory structure ====="
          tree -L 2
          echo "===== Config.toml ====="
          cat config.toml
          echo "===== Templates ====="
          ls -l templates/
          echo "===== Content ====="
          ls -l content/

      - name: Build Site
        run: zola build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'public'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
